networks:
  rproxy:
    external: true

volumes:
  homarr-appdata:
    external: true

services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    environment:
      SECRET_ENCRYPTION_KEY: e692c21541f04b04cd748c8f507006380e8f46dfa5bdb32a878a70b3e87c9b0b
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:7575 >/dev/null 2>&1 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - homarr-appdata:/appdata
    ports:
      - 127.0.0.1:7575:7575
    networks:
      - rproxy
    restart: unless-stopped
