networks:
  rproxy:
    name: rproxy
    external: true

volumes:
  prowlarr-config:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid
    volumes:
      - prowlarr-config:/config
    ports:
      - 127.0.0.1:9696:9696
    networks:
      - rproxy
    restart: unless-stopped
