networks:
  rproxy:
    external: true

volumes:
  grafana-data:
    external: true
  grafana-plugins:
    external: true

services:
  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SERVER_ROOT_URL: https://grafana.dunderdev.duckdns.org
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:3000/api/health > /dev/null 2>&1 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-plugins:/var/lib/grafana/plugins
    networks:
      - rproxy
    restart: unless-stopped
