networks:
  rproxy:
    external: true

volumes:
  jellyfin-config:
    external: true
  jellyfin-cache:
    external: true
  jellyfin-movies:
    external: true
  jellyfin-series:
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8096 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - jellyfin-movies:/movies
      - jellyfin-series:/series
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 127.0.0.1:8096:8096
    networks:
      - rproxy
    restart: unless-stopped
