networks:
  rproxy:
    external: true

volumes:
  portainer-data:
    external: true

services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rproxy
    restart: unless-stopped
