global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Node Exporter metrics
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # cAdvisor container metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
